message: This is a message defined in the configuration file config.yml.
messageRepetitions: 3
authUser: swzhou
authPassword: secret
server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1
  adminConnectors:
    - type: http
      port: 8081
database:
  driverClass: com.mysql.jdbc.Driver
  user: phonebookuser
  password: phonebookpassword
  url: jdbc:mysql://localhost:9889/phonebook